
deployment:
  staging:
    branch: master
    commands:
      - git push git@heroku.com:covered-staging.git $CIRCLE_SHA1:master
      - heroku run rake db:migrate --app covered-staging

machine:
  environment:
    MULTIFY_FILEPICKER_API_KEY: AoHaLq8oRH9Dy9MVuTTvwz
