FORMAT: 1A
HOST: https://threadable.com/

# Threadable
Threadable is a *better mailing list* for group discussions. This API lets you control it from your application!

# Authentication
To authenticate, you need a token. Get the token from your user profile page, https://threadable.com/profile

At the bottom of the page, there's an API token section. Hit generate, and you'll get an access token.

Then just append your token to the request. For instance, if you wanted to get the current user,
`https://threadable.com/api/users/current.json?access_token=YOUR_TOKEN_HERE`

You can also put the token in the `Access-Token:` HTTP header on your request. Use this method if you'd like to
query the API with Apiary.

**Be careful with your token**, since it confers access to your Threadable account. If you ever need to revoke
it, just hit the *Regenerate* button and you'll get a new one.

*Oauth2 coming soon!*

# Group Organizations
An Organization can contain many groups, conversations, and messages. A user can be a member of many organizations.

## Organizations Collection [/api/organizations]
### List all Organizations [GET]
+ Response 200 (application/json)

        {
          "organizations":[
            {
              "id":3,
              "param":"raceteam",
              "name":"UCSD Electric Racing",
              "short_name":"RaceTeam",
              "slug":"raceteam",
              "subject_tag":"RaceTeam",
              "description":"Senior engineering electric race team!",
              "has_held_messages":false,
              "trusted":true,
              "email_address_username":"raceteam",
              "email_address":"raceteam@threadable.com",
              "task_email_address":"raceteam+task@threadable.com",
              "formatted_email_address":"UCSD Electric Racing \u003craceteam@threadable.com\u003e",
              "formatted_task_email_address":"UCSD Electric Racing Tasks \u003craceteam+task@threadable.com\u003e",
              "groups":[
                {
                  "id":8,
                  "slug":"press",
                  "name":"Press",
                  "email_address_tag":"press",
                  "subject_tag":"RaceTeam+Press",
                  "color":"#e67e22",
                  "auto_join":false,
                  "hold_messages":true,
                  "alias_email_address":"Press Enquiries \u003cpress@ucsd.example.com\u003e",
                  "webhook_url":"",
                  "email_address":"press@ucsd.example.com",
                  "task_email_address":"press-task@ucsd.example.com",
                  "formatted_email_address":"Press Enquiries \u003cpress@ucsd.example.com\u003e",
                  "formatted_task_email_address":"Press Enquiries Tasks \u003cpress-task@ucsd.example.com\u003e",
                  "internal_email_address":"raceteam+press@threadable.com",
                  "internal_task_email_address":"raceteam+press+task@threadable.com",
                  "conversations_count":0,
                  "members_count":2,
                  "organization_slug":"raceteam",
                  "current_user_is_a_member":false
                },
                {
                  "id":7,
                  "slug":"graphic-design",
                  "name":"Graphic Design",
                  "email_address_tag":"graphic-design",
                  "subject_tag":"RaceTeam+Graphic Design",
                  "color":"#f2ad40",
                  "auto_join":true,
                  "hold_messages":true,
                  "alias_email_address":"",
                  "webhook_url":"",
                  "email_address":"raceteam+graphic-design@threadable.com",
                  "task_email_address":"raceteam+graphic-design+task@threadable.com",
                  "formatted_email_address":"\"UCSD Electric Racing: Graphic Design\" \u003craceteam+graphic-design@threadable.com\u003e",
                  "formatted_task_email_address":"\"UCSD Electric Racing: Graphic Design Tasks\" \u003craceteam+graphic-design+task@threadable.com\u003e",
                  "internal_email_address":"raceteam+graphic-design@threadable.com",
                  "internal_task_email_address":"raceteam+graphic-design+task@threadable.com",
                  "conversations_count":1,
                  "members_count":9,
                  "organization_slug":"raceteam",
                  "current_user_is_a_member":false
                }
              ]
            }
          ]
        }

## Organization [/api/organizations/{id}]
A single Organization object with all its details.

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Organization to perform action with. Has example value.

### Retrieve an Organization [GET]
+ Response 200 (application/json)

    + Body

            {
              "id":3,
              "param":"raceteam",
              "name":"UCSD Electric Racing",
              "short_name":"RaceTeam",
              "slug":"raceteam",
              "subject_tag":"RaceTeam",
              "description":"Senior engineering electric race team!",
              "has_held_messages":false,
              "trusted":true,
              "email_address_username":"raceteam",
              "email_address":"raceteam@threadable.com",
              "task_email_address":"raceteam+task@threadable.com",
              "formatted_email_address":"UCSD Electric Racing \u003craceteam@threadable.com\u003e",
              "formatted_task_email_address":"UCSD Electric Racing Tasks \u003craceteam+task@threadable.com\u003e",
              "groups":[
                {
                  "id":8,
                  "slug":"press",
                  "name":"Press",
                  "email_address_tag":"press",
                  "subject_tag":"RaceTeam+Press",
                  "color":"#e67e22",
                  "auto_join":false,
                  "hold_messages":true,
                  "alias_email_address":"Press Enquiries \u003cpress@ucsd.example.com\u003e",
                  "webhook_url":"",
                  "email_address":"press@ucsd.example.com",
                  "task_email_address":"press-task@ucsd.example.com",
                  "formatted_email_address":"Press Enquiries \u003cpress@ucsd.example.com\u003e",
                  "formatted_task_email_address":"Press Enquiries Tasks \u003cpress-task@ucsd.example.com\u003e",
                  "internal_email_address":"raceteam+press@threadable.com",
                  "internal_task_email_address":"raceteam+press+task@threadable.com",
                  "conversations_count":0,
                  "members_count":2,
                  "organization_slug":"raceteam",
                  "current_user_is_a_member":false
                },
                {
                  "id":7,
                  "slug":"graphic-design",
                  "name":"Graphic Design",
                  "email_address_tag":"graphic-design",
                  "subject_tag":"RaceTeam+Graphic Design",
                  "color":"#f2ad40",
                  "auto_join":true,
                  "hold_messages":true,
                  "alias_email_address":"",
                  "webhook_url":"",
                  "email_address":"raceteam+graphic-design@threadable.com",
                  "task_email_address":"raceteam+graphic-design+task@threadable.com",
                  "formatted_email_address":"\"UCSD Electric Racing: Graphic Design\" \u003craceteam+graphic-design@threadable.com\u003e",
                  "formatted_task_email_address":"\"UCSD Electric Racing: Graphic Design Tasks\" \u003craceteam+graphic-design+task@threadable.com\u003e",
                  "internal_email_address":"raceteam+graphic-design@threadable.com",
                  "internal_task_email_address":"raceteam+graphic-design+task@threadable.com",
                  "conversations_count":1,
                  "members_count":9,
                  "organization_slug":"raceteam",
                  "current_user_is_a_member":false
                }
              ]
            }

# Group Groups

## Groups collection [/api/groups]
### Create a Group [POST]
+ Request (application/json)

        {
          "group":{
            "name":"Graphic Design",
            "email_address_tag":"graphic-design",
            "subject_tag":"Design",
            "color":"#D35400",
            "auto_join":false,
            "hold_messages":false
          },
          "organization_id":"raceteam"
        }

+ Response 201 (application/json)

        {
          "id":7,
          "slug":"graphic-design",
          "name":"Graphic Design",
          "email_address_tag":"graphic-design",
          "subject_tag":"RaceTeam+Graphic Design",
          "color":"#f2ad40",
          "auto_join":true,
          "hold_messages":true,
          "alias_email_address":"",
          "webhook_url":"",
          "email_address":"raceteam+graphic-design@threadable.com",
          "task_email_address":"raceteam+graphic-design+task@threadable.com",
          "formatted_email_address":"\"UCSD Electric Racing: Graphic Design\" \u003craceteam+graphic-design@threadable.com\u003e",
          "formatted_task_email_address":"\"UCSD Electric Racing: Graphic Design Tasks\" \u003craceteam+graphic-design+task@threadable.com\u003e",
          "internal_email_address":"raceteam+graphic-design@threadable.com",
          "internal_task_email_address":"raceteam+graphic-design+task@threadable.com",
          "conversations_count":1,
          "members_count":9,
          "organization_slug":"raceteam",
          "current_user_is_a_member":false
        }

## Group [/api/groups/{id}]
A single Group object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Group to perform action with. Has example value.

### Retrieve a Group [GET]
+ Response 200 (application/json)

        {
          "id":7,
          "slug":"graphic-design",
          "name":"Graphic Design",
          "email_address_tag":"graphic-design",
          "subject_tag":"RaceTeam+Graphic Design",
          "color":"#f2ad40",
          "auto_join":true,
          "hold_messages":true,
          "alias_email_address":"",
          "webhook_url":"",
          "email_address":"raceteam+graphic-design@threadable.com",
          "task_email_address":"raceteam+graphic-design+task@threadable.com",
          "formatted_email_address":"\"UCSD Electric Racing: Graphic Design\" \u003craceteam+graphic-design@threadable.com\u003e",
          "formatted_task_email_address":"\"UCSD Electric Racing: Graphic Design Tasks\" \u003craceteam+graphic-design+task@threadable.com\u003e",
          "internal_email_address":"raceteam+graphic-design@threadable.com",
          "internal_task_email_address":"raceteam+graphic-design+task@threadable.com",
          "conversations_count":1,
          "members_count":9,
          "organization_slug":"raceteam",
          "current_user_is_a_member":false
        }

### Update a Group [PUT]
+ Request (application/json)

        {
          "group":{
            "subject_tag":"Design",
            "color":"#D35400",
            "auto_join":false,
            "hold_messages":false,
            "alias_email_address":"Design Team \u003cdesign@ucsd.example.com\u003e",
            "webhool_url":"http://example.com/hookreceiver"
          },
          "organization_id":"raceteam"
        }

+ Response 201 (application/json)

        {
          "id":7,
          "slug":"graphic-design",
          "name":"Graphic Design",
          "email_address_tag":"graphic-design",
          "subject_tag":"RaceTeam+Graphic Design",
          "color":"#f2ad40",
          "auto_join":true,
          "hold_messages":true,
          "alias_email_address":"Design Team \u003cdesign@ucsd.example.com\u003e",
          "webhool_url":"http://example.com/hookreceiver",
          "email_address":"raceteam+graphic-design@threadable.com",
          "task_email_address":"raceteam+graphic-design+task@threadable.com",
          "formatted_email_address":"\"UCSD Electric Racing: Graphic Design\" \u003craceteam+graphic-design@threadable.com\u003e",
          "formatted_task_email_address":"\"UCSD Electric Racing: Graphic Design Tasks\" \u003craceteam+graphic-design+task@threadable.com\u003e",
          "internal_email_address":"raceteam+graphic-design@threadable.com",
          "internal_task_email_address":"raceteam+graphic-design+task@threadable.com",
          "conversations_count":1,
          "members_count":9,
          "organization_slug":"raceteam",
          "current_user_is_a_member":false
        }

### Remove a Group [DELETE]
+ Response 204

## Group join action [/api/groups/{id}/join]
Add the current user to a group

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Group to perform action with. Has example value.

### Join a Group [POST]
+ Request

        (empty)

+ Response 200 (application/json)

        {
          "id":7,
          "slug":"graphic-design",
          "name":"Graphic Design",
          "email_address_tag":"graphic-design",
          "subject_tag":"RaceTeam+Graphic Design",
          "color":"#f2ad40",
          "auto_join":true,
          "hold_messages":true,
          "alias_email_address":"",
          "webhook_url":"",
          "email_address":"raceteam+graphic-design@threadable.com",
          "task_email_address":"raceteam+graphic-design+task@threadable.com",
          "formatted_email_address":"\"UCSD Electric Racing: Graphic Design\" \u003craceteam+graphic-design@threadable.com\u003e",
          "formatted_task_email_address":"\"UCSD Electric Racing: Graphic Design Tasks\" \u003craceteam+graphic-design+task@threadable.com\u003e",
          "internal_email_address":"raceteam+graphic-design@threadable.com",
          "internal_task_email_address":"raceteam+graphic-design+task@threadable.com",
          "conversations_count":1,
          "members_count":9,
          "organization_slug":"raceteam",
          "current_user_is_a_member":false
        }

## Group leave action [/api/groups/{id}/leave]
Remove the current user from a group

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Group to perform action with. Has example value.

### Leave a Group [POST]
+ Request

        (empty)

+ Response 200 (application/json)

        {
          "id":7,
          "slug":"graphic-design",
          "name":"Graphic Design",
          "email_address_tag":"graphic-design",
          "subject_tag":"RaceTeam+Graphic Design",
          "color":"#f2ad40",
          "auto_join":true,
          "hold_messages":true,
          "alias_email_address":"",
          "webhook_url":"",
          "email_address":"raceteam+graphic-design@threadable.com",
          "task_email_address":"raceteam+graphic-design+task@threadable.com",
          "formatted_email_address":"\"UCSD Electric Racing: Graphic Design\" \u003craceteam+graphic-design@threadable.com\u003e",
          "formatted_task_email_address":"\"UCSD Electric Racing: Graphic Design Tasks\" \u003craceteam+graphic-design+task@threadable.com\u003e",
          "internal_email_address":"raceteam+graphic-design@threadable.com",
          "internal_task_email_address":"raceteam+graphic-design+task@threadable.com",
          "conversations_count":1,
          "members_count":9,
          "organization_slug":"raceteam",
          "current_user_is_a_member":false
        }


# Group Conversations

# Group Tasks

# Group Messages

# Group Events

# Group Users

# Group Organization Members

# Group Group Members

# Group Task Doers


# Group Notes (this is an example from apiary, make sure to delete it)
Notes related resources of the **Notes API**

## Notes Collection [/notes]
### List all Notes [GET]
+ Response 200 (application/json)

        [{
          "id": 1, "title": "Jogging in park"
        }, {
          "id": 2, "title": "Pick-up posters from post-office"
        }]

### Create a Note [POST]
+ Request (application/json)

        { "title": "Buy cheese and bread for breakfast." }

+ Response 201 (application/json)

        { "id": 3, "title": "Buy cheese and bread for breakfast." }

## Note [/notes/{id}]
A single Note object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Note to perform action with. Has example value.

### Retrieve a Note [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 2, "title": "Pick-up posters from post-office" }

### Remove a Note [DELETE]
+ Response 204
