source 'https://rubygems.org'
gem 'rails', '3.2.9'

gem 'virtus'

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'
gem "haml", ">= 3.1.6"
gem "haml-rails", ">= 0.3.4", :group => :development
gem "bootstrap-sass", ">= 2.0.4.0"


group :test, :development do
  gem 'debugger'
  gem 'cucumber-rails'
  gem 'rspec-rails'
end
