#!/usr/bin/env ruby

require 'rubygems'
require 'bundler'
Bundler.setup

require 'listen'

ROOT = Pathname.new File.expand_path('../../',__FILE__)



Listen.to(ROOT+'stylesheets') do |modified, added, removed|
  # ...
end
