development:
  adapter: postgresql
  encoding: utf8
  database: multify_development
  pool: 5
  username: postgres
  password: password

test:
  adapter: postgresql
  encoding: utf8
  database: multify_test
  pool: 5
  username: postgres
  password: password
