development:
  key: 'INTENTIONALLY LEFT BLANK'
  password: 'INTENTIONALLY LEFT BLANK'

test:
  key: 'INTENTIONALLY LEFT BLANK'
  password: 'INTENTIONALLY LEFT BLANK'

production:
  key: <%= ENV['THREADABLE_MAILGUN_KEY'] %>
  password: <%= ENV['THREADABLE_MAILGUN_PASSWORD'] %>

staging:
  key: <%= ENV['THREADABLE_MAILGUN_KEY'] %>
  password: <%= ENV['THREADABLE_MAILGUN_PASSWORD'] %>
