groups:
  -
    name: Social
    subject_tag: Social
    color: "#3498db"
    email_address_tag: social
  -
    name: Random
    subject_tag: Random
    color: "#8e44ad"
    email_address_tag: random

conversations:
  -
    group:
    subject: I am your welcome message. In ungrouped.
    body_plain: I am the message plaintext
    body_html: <b>I am the message content</b>
    from: Threadable Support <support@threadable.com>
    to_header: Threadable Support <support@threadable.com>
  -
    group: social
    subject: I am your welcome message for the social group.
    body_plain: "I explain how groups work, probably"
    body_html: "<b>I explain how groups work, as html</b>"
    from: Threadable Support <support@threadable.com>
    to_header: Threadable Support <support@threadable.com>
  -
    group:
    subject: I am a demo task.
    body_plain: I am the message plaintext
    body_html: <b>I am the message content</b>
    task: true
    from: Threadable Support <support@threadable.com>
    to_header: Threadable Support <support@threadable.com>
