groups:
  -
    name: Social
    subject_tag: Social
    color: "#3498db"
    email_address_tag: social

conversations:
  welcome:
    subject: 'Welcome to Threadable!'
    task: false
    delay_hours: 0
    from: "Aaron at Threadable <aaron@threadable.com>"
  add_members:
    subject: 'Add some more members'
    task: true
    delay_hours: 1
    from: "Aaron at Threadable <aaron@threadable.com>"
  tips_buttons:
    subject: 'Threadable Tips'
    task: false
    delay_hours: 24
    from: "Aaron at Threadable <aaron@threadable.com>"
  tips_groups:
    subject: 'Threadable Tips'
    task: false
    delay_hours: 72
    from: "Aaron at Threadable <aaron@threadable.com>"
    parent_slug: 'threadable-tips'
  # tips_commands:
  #   subject: 'Threadable Tips'
  #   task: false
  #   delay_hours: 120
  #   from: "Aaron at Threadable <aaron@threadable.com>"
  #   parent_slug: 'threadable-tips'
