#!/bin/sh

export RAILS_ENV=test
export RACK_ENV=test
export SELENIUM=false

bundle check || bundle install
bundle exec rake --trace --verbose db:schema:load || exit 1
bundle exec rspec --format documentation --order random || exit 1
bundle exec cucumber
