#!/bin/sh

export RAILS_ENV=test
export RACK_ENV=test
export MULTIFY_SELENIUM=false

bundle check || bundle install
bundle exec rake --trace --verbose db:schema:load || exit 1
bundle exec rspec --format documentation --order random && \
bundle exec cucumber
