#!/bin/sh

export RAILS_ENV=test
export RACK_ENV=test
export SELENIUM_BROWSER=chrome

bundle check || bundle install
bundle exec rake db:schema:load || exit 1
bundle exec rspec --format Fuubar --order random || exit 1
