#!/bin/bash


bundle exec rspec --require rspec/instafail --format RSpec::Instafail
exit_code=$?

if [ ${CIRCLE_ARTIFACTS:+x} ]
then
  mkdir $CIRCLE_ARTIFACTS/tmp
  cp -r tmp/* $CIRCLE_ARTIFACTS/tmp
fi

exit $exit_code
