#!/usr/bin/env ruby

require 'pathname'

CIRCLE_NODE_TOTAL = ENV['CIRCLE_NODE_TOTAL'].to_i
CIRCLE_NODE_INDEX = ENV['CIRCLE_NODE_INDEX'].to_i
CIRCLE_ARTIFACTS  = ENV['CIRCLE_ARTIFACTS']

RAILS_ROOT = Pathname File.expand_path('../../', __FILE__)

spec_dir = case ENV['CIRCLE_BRANCH']
when 'staging';    'staging_spec'
when 'production'; 'production_spec'
else;              'spec'
end

ALL_SPECS = Dir[RAILS_ROOT.join("#{spec_dir}/**/*_spec.rb")].map do |path|
  Pathname(path).relative_path_from(RAILS_ROOT).to_s
end.uniq.sort

GROUPED_SPECS = ALL_SPECS.each_with_index.group_by do |spec, index|
  index % CIRCLE_NODE_TOTAL
end

MY_SPECS = GROUPED_SPECS[CIRCLE_NODE_INDEX].map(&:first)

puts "Running specs:"
puts MY_SPECS.map{|x| "  #{x}"}
puts
COMMAND = %(
  bundle exec rspec
  --colour
  --backtrace
  --require ./spec/support/list_failures_formatter.rb
  --format ListFailuresFormatter
  --out #{File.join(CIRCLE_ARTIFACTS, 'rspec-failures.txt').inspect}
  --require ./spec/support/documentation_instafail_formatter.rb
  --format DocumentationInstafail
  #{MY_SPECS.map(&:inspect).join(' ')}
).gsub(/\s*\n\s*/, ' ')
puts
puts COMMAND
exec COMMAND
