#!/usr/bin/env ruby

case ARGV.first
when 'staging'
  exec 'heroku run console --app threadable-staging'
when 'production'
  exec 'heroku run console --app threadable-production'
when 'local'
  exec 'bundle exec rails c'
else
  exec 'bundle exec rails c'
end


