#!/bin/bash
set -e -x

ENV=$1

if [ $ENV == 'production' ]
  then
    BRANCH=origin
    REFSPEC="--tag latest-staging"
elif [ $ENV == 'staging' ]
  then
    REFSPEC=HEAD
    BRANCH=HEAD
  else
    echo 'Expected production or staging'
    exit 1
fi

#circleci now requires this incantation to deploy properly
[[ ! -s "$(git rev-parse --git-dir)/shallow" ]] || git fetch --unshallow

# update local tags
git fetch --tags

# push to github
git push git@heroku.com:threadable-$ENV.git $REFSPEC:master || exit 1

# run migrations
heroku run rake db:migrate --app threadable-$ENV

# tag this rev as having been released
git push --delete origin latest-$ENV
git tag -f latest-$ENV $BRANCH
git push --tags
