#!/bin/sh

ENV=${1:-staging}

# run CI
script/ci || exit

# push to CI
git push $ENV master || exit

# tag this rev as having been released
git push --delete origin latest-$ENV
git tag -f latest-$ENV
git push --tags
