#!/usr/bin/env ruby

require 'bundler/setup'
require 'dotenv'
Dotenv.load!

ENV['DB_POOL'] = ENV['THREADABLE_WORKER_THREAD_COUNT']

exec %( echo bundle exec sidekiq -c $THREADABLE_WORKER_THREAD_COUNT )
