#!/usr/bin/env ruby

if ENV['RAILS_ENV'].nil? || ENV['RAILS_ENV'] == 'development'
  require 'bundler/setup'
  require 'dotenv'
  Dotenv.load!
end

ENV['DB_POOL'] = ENV['THREADABLE_WORKER_THREAD_COUNT']

exec %( bundle exec sidekiq -c $THREADABLE_WORKER_THREAD_COUNT )
