source "https://rubygems.org"

gem "sinatra", :require => "sinatra/base"
gem "compass"
gem "haml"
gem "sprockets"
gem "json"

#gem "shotgun"
gem "debugger"


gem "chunky_png"


gem 'rb-fsevent', '~> 0.9.1'
gem "listen"


gem 'hpricot'
