//= require "jquery"
//= require "underscore"
//= require "backbone"
// //= require "ejs"
//= require "bootstrap"

//= require "multify"
//= require "multify/templates"
//= require "multify/router"
//= require_tree "./multify/views"
//= require "multify/user"
//= require "multify/project"
