//= require "uri"
//= require "jquery"
//= require "jquery-cookie"
//= require "underscore"
//= require "backbone"
// //= require "ejs"
//= require "bootstrap"

//= require "multify"
//= require "multify/request"
//= require "multify/session"
//= require "multify/authentication"
//= require "multify/templates"
//= require "multify/router"
//= require_tree "./multify/views"
//= require "multify/user"
//= require "multify/project"
//= require "multify/projects"
