//= require "multify/core"
//= require "multify/backbone"
//= require "multify/request"
//= require "multify/session"
//= require "multify/templates"
//= require "multify/router"
//= require "multify/routes"
//= require_tree "./multify/views"
//= require "multify/user"
//= require "multify/project"
//= require "multify/projects"
//= require "multify/task"
//= require "multify/tasks"
//= require "multify/authentication"

